# This is a basic workflow to help you get started with Actions

name: py

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8 #install the python needed

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          python run.py
        env:
            key: ${{ secrets.key }}
        
